import type { Command } from 'commander';

import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import path from 'node:path';

import { REPO_ROOT } from '../lib/paths.js';
import { bad, ok } from '../lib/print.js';
import { run } from '../lib/run.js';

export const CODEX_TYPES_DIR = path.join(REPO_ROOT, 'src', 'codex', 'generated');

// What src/codex uses. Everything they import comes along, nothing else.
const ROOTS = [
  'InitializeParams.ts',
  'InitializeResponse.ts',
  'v2/ThreadArchiveParams.ts',
  'v2/ThreadLoadedListParams.ts',
  'v2/ThreadLoadedListResponse.ts',
  'v2/ThreadQueueAddParams.ts',
  'v2/ThreadQueueAddResponse.ts',
  'v2/ThreadReadParams.ts',
  'v2/ThreadStartParams.ts',
  'v2/ThreadStatus.ts',
];

// The daemon updates itself apart from the CLI, so types come from the daemon's own binary.
const DAEMON_BIN = path.join(homedir(), '.codex', 'packages', 'app-server-daemon', 'current', 'bin', 'codex');

const IMPORT = /from "(\.{1,2}\/[^"]+)"/g;

/** The `roots` and every file they import, with `.js` on each import and a header naming `version`. */
export function typeClosure({
  read,
  roots,
  version,
}: {
  read: (file: string) => string;
  roots: string[];
  version: string;
}) {
  const header = `// Generated by \`pnpm messhall-dev codex-types\` from the app-server daemon, ${version}.\n`;
  const files: Record<string, string> = {};
  const todo = [...roots];
  for (let file = todo.pop(); file !== undefined; file = todo.pop()) {
    if (files[file] === undefined) {
      const text = read(file);
      const from = path.posix.dirname(file);
      todo.push(...Array.from(text.matchAll(IMPORT), match => path.posix.join(from, `${match[1]}.ts`)));
      files[file] = header + text.replaceAll(IMPORT, (_all, spec: string) => `from "${spec}.js"`);
    }
  }
  return files;
}

async function codexTypes() {
  const bin = existsSync(DAEMON_BIN) ? DAEMON_BIN : 'codex';
  const version = (await run(bin, ['--version'], tmpdir())).stdout.trim();
  const out = mkdtempSync(path.join(tmpdir(), 'messhall-codex-ts-'));
  try {
    const generated = await run(bin, ['app-server', 'generate-ts', '--experimental', '--out', out], tmpdir());
    if (generated.code !== 0) return { code: 1, report: bad(`generate-ts failed: ${generated.stderr.trim()}`) };
    const files = typeClosure({ read: file => readFileSync(path.join(out, file), 'utf8'), roots: ROOTS, version });
    rmSync(CODEX_TYPES_DIR, { force: true, recursive: true });
    Object.entries(files).forEach(([file, text]) => {
      mkdirSync(path.dirname(path.join(CODEX_TYPES_DIR, file)), { recursive: true });
      writeFileSync(path.join(CODEX_TYPES_DIR, file), text);
    });
    return { code: 0, report: ok(`wrote ${Object.keys(files).length} files from ${version} to src/codex/generated`) };
  } finally {
    rmSync(out, { force: true, recursive: true });
  }
}

/** Registers `codex-types`. */
export function registerCodexTypes(program: Command) {
  program
    .command('codex-types')
    .description("Regenerate src/codex/generated from the Codex app-server daemon's own binary.")
    .action(async () => {
      const result = await codexTypes();
      console.log(result.report);
      process.exitCode = result.code;
    });
}
