import { describe, expect, it } from 'vitest';

import { typeClosure } from '../../tools/dev/commands/codexTypes.js';

const FILES: Record<string, string> = {
  'Unused.ts': 'export type Unused = string;\n',
  'serde_json/JsonValue.ts': 'export type JsonValue = string;\n',
  'v2/Status.ts': 'export type Status = { "type": "idle" };\n',
  'v2/ThreadRead.ts':
    '// GENERATED CODE! DO NOT MODIFY BY HAND!\nimport type { JsonValue } from "../serde_json/JsonValue";\nimport type { Status } from "./Status";\n\nexport type ThreadRead = { status: Status, extra: JsonValue };\n',
};

describe('typeClosure', () => {
  it('keeps the roots and what they import, with .js imports and the version header', () => {
    const files = typeClosure({ read: file => FILES[file]!, roots: ['v2/ThreadRead.ts'], version: 'codex-cli 9.9.9' });

    expect(Object.keys(files).sort()).toStrictEqual(['serde_json/JsonValue.ts', 'v2/Status.ts', 'v2/ThreadRead.ts']);
    expect(files['v2/ThreadRead.ts']).toBe(
      '// Generated by `pnpm messhall-dev codex-types` from the app-server daemon, codex-cli 9.9.9.\n// GENERATED CODE! DO NOT MODIFY BY HAND!\nimport type { JsonValue } from "../serde_json/JsonValue.js";\nimport type { Status } from "./Status.js";\n\nexport type ThreadRead = { status: Status, extra: JsonValue };\n',
    );
  });
});
